---
title: "Untitled"
author: "Praveen Arora"
date: "26/08/2020"
output: html_document
---

## R Markdown


The run_analysis.R script performs the data preparation and then followed by the 5 steps required as described in the course project’s definition.

Download the dataset
Dataset downloaded and extracted under the folder called UCI HAR Dataset

Assign each data to variables

features <- features.txt : 561 rows, 2 columns
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ.

activities <- activity_labels.txt : 6 rows, 2 columns

List of activities performed when the corresponding measurements were taken and its codes (labels)

subject_test <- test/subject_test.txt
contains test data of test subjects being observed

xtest <- test/X_test.txt :
contains recorded features test data

ytest <- test/y_test.txt :
contains test data of activities’code labels

subject_train <- test/subject_train.txt: 
contains train data of subjects being observed

xtrain <- test/X_train.txt :
contains recorded features train data

ytrain <- test/y_train.txt : 
contains train data of activities’code labels

Merges the training and the test sets to create one data set

x is created by merging x_train and x_test using rbind() function

y  is created by merging y_train and y_test using rbind() function

subject is created by merging subject_train and subject_test using rbind() function

mergeddata is created by merging Subject, Y and X using cbind() function

Extracts only the measurements on the mean and standard deviation for each measurement

tidy  is created by subsetting mergeddata, selecting only columns: subject, code and the measurements on the mean and standard deviation (std) for each measurement

Uses descriptive activity names to name the activities in the data set

Entire numbers in code column of the tidy replaced with corresponding activity taken from second column of the activities variable

Appropriately labels the data set with descriptive variable names
code column in tidy renamed into activities
All Acc in column’s name replaced by accelerometer
All Gyro in column’s name replaced by gyroscope
All BodyBody in column’s name replaced by body
All Mag in column’s name replaced by magnitude
All start with character f in column’s name replaced by frequency
All start with character t in column’s name replaced by time

From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject

finaldata is created by sumarizing TidyData taking the means of each variable for each activity and each subject, after groupped by subject and activity.
Export finaldata into finaldata.txt file.

